import Head from 'next/head';
import React  from 'react';


export default function Second() {

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/public/favicon.ico' />
      </Head>
      <h1>Second</h1>
    </div>
  );
}
